name: nations
description: queen support for localization in flutter, part of queen framework
version: 0.0.6
homepage: https://github.com/FlutterQueen/nations
issue_tracker: https://github.com/FlutterQueen/nations/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  nations_assets: ^0.0.1
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
