name: nations
description: queen support for localization in flutter
version: 0.0.3
homepage: https://github.com/maxzod/nations

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # provider: ^6.0.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  assets:
    - assets/lang/
