#The name of your workflow.
name: coverage
# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      - name: test converage
      - uses: codecov/codecov-action@v1.0.7
